## multichain cross-chain router Protocol
name: "fetch Ink-protocol Party"

on:
  schedule:
    - cron: "45 14 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "check codes"
        uses: actions/checkout@master
      - name: "Run fetchInkPartyInfo.sh" # 执行shell命令文件
        run: bash fetchInkPartyInfo.sh
